NumPy is a python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

NumPy aims to provide an array object that is up to 50x faster that traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

In [2]:
import numpy as np

print(np.__version__)

1.18.1


In [4]:
arr = np.array([1, 2, 3, 4, 5]) # using list

print(arr)

print(type(arr))

arr = np.array((1, 2, 3, 4, 5)) # using tuple

print(arr)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [5]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [9]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

6
Last element from 2nd dim:  10


In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

print(arr[1:5:2])

print(arr[::2])

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[5 6]
[2 4]
[1 3 5 7]
[3 8]
[[2 3 4]
 [7 8 9]]


In [25]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype) # U - unicode string

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)


arr = np.array([1, 2, 3, 4], dtype='i4')  #i4 -> 4 bytes integer:
print(arr)
print(arr.dtype)

# If a type is given in which elements can't be casted then NumPy will raise a ValueError.
# ValueError: In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.
# arr = np.array(['a', '2', '3'], dtype='i') # ValueError: invalid literal for int() with base 10: 'a'

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)


arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

int64
<U6
[b'1' b'2' b'3' b'4']
|S1
[1 2 3 4]
int32
[1 2 3]
int32
[1 2 3]
int64
[ True False  True]
bool


In [28]:
# copy

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

#view
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)


# Every NumPy array has the attribute base that returns None if the array owns the data.
# Otherwise, the base  attribute refers to the original object.

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base) #The copy returns None.
print(y.base) #The view returns the original array.

[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]
None
[1 2 3 4 5]


In [30]:
# shape

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

(2, 4)
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [38]:
# Reshape
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

print()

newarr2 = arr.reshape(2, 3, 2)

print(newarr2)

print(newarr2.base) # prints original array, means it is view ( not copy )

print()

#You are allowed to have one "unknown" dimension.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

print()

# Flatten : multi to 1D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

[1 2 3 4 5 6]


In [43]:
# iterate
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)
    
# nditer : for multi dimension
for x in np.nditer(arr): 
  print(x)

# iterate with step size
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)


#ndenumerate : index and value
for idx, x in np.ndenumerate(arr):
  print(idx, x)

1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12
1
3
5
7
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [58]:
# Join
#  in NumPy we join arrays by axes. If axis is not explicitly passed, it is taken as 0.

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arrAx0 = np.concatenate((arr1, arr2), axis=0)
print(arrAx0)
arrAx1 = np.concatenate((arr1, arr2), axis=1)
print(arrAx1)


# stack : can be done along a new axis.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)

print(arr)

# hstack : horizontal stack
arr = np.hstack((arr1, arr2))

print(arr)

# vstack : vertical stack
arr = np.vstack((arr1, arr2))

print(arr)

# dstack : depth stack
arr = np.dstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


In [77]:
# split
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

# If the array has less elements than required, it will adjust from the end accordingly.
newarr = np.array_split(arr, 4)

print(newarr)

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

# axis can be used to split
newarr = np.array_split(arr, 3, axis=1)

print(newarr)

#hsplit, vsplit, dsplit

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]


In [75]:
# Search
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

# searchsorted
# performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

#
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

(array([3, 5, 6]),)
(array([1, 3, 5, 7]),)
1
[1 2 3]


In [79]:
# Sort
# This method returns a copy of the array, leaving the original array unchanged.
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))


arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[0 1 2 3]
[[2 3 4]
 [0 1 5]]


In [82]:
# Filter
# A boolean index list is a list of booleans corresponding to indexes in the array.
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[41 43]
[False False  True  True]
[43 44]
[False  True False  True False  True False]
[2 4 6]


In [89]:
# Random
from numpy import random

x = random.randint(100)

print(x)

#  rand() method returns a random float between 0 and 1.
x = random.rand()

print(x)


x=random.randint(100, size=(5))

print(x)

x = random.randint(100, size=(3, 5))

print(x)


# random floats
x = random.rand(3, 5)

print(x)

# choice() method takes an array as a parameter and randomly returns value
x = random.choice([3, 5, 7, 9])

print(x)

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

0
0.07962482748472155
[79 41 76 11 71]
[[54 49 41 38 75]
 [72 48 88 33 52]
 [15  4  2 91 63]]
[[0.97135781 0.49926016 0.02596789 0.38492027 0.63320246]
 [0.27728281 0.47448309 0.8546419  0.89417381 0.41187351]
 [0.1992615  0.36991161 0.47112868 0.64411623 0.20081349]]
3
[[9 7 7 9 9]
 [3 3 9 5 7]
 [9 5 9 7 9]]


In [94]:
# ufuncs stands for "Universal Functions" and they are NumPy functions that operates on the ndarray object.
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

[ 5  7  9 11]


In [112]:
# others

o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
print(o)

print(np.ones((3, 2)))

print(np.zeros((2, 3)))

print(np.eye(3))

y = [1, 3, 2]
print(np.diag(y))

print(np.repeat([1, 2, 3], 3))

p = np.ones([2, 3], int)
print(np.vstack([p, 2*p]))
print(np.hstack([p, 2*p]))

x = np.array([1, 2, 3])
x = np.array([4, 5, 6])
print(x.dot(y)) # dot product  1*4 + 2*5 + 3*6

x.T.shape


a = np.array([-4, -2, 1, 3, 5])
print(a.mean())
print(a.max())
print(a.std())
print(a.argmax())
print(a.argmin())

test = np.random.randint(0, 10, (4,3))
test2 = test**2
print(test)
print(test2)
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4. ]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 3 0]
 [0 0 2]]
[1 1 1 2 2 2 3 3 3]
[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]]
[[1 1 1 2 2 2]
 [1 1 1 2 2 2]]
31
0.6
5
3.2619012860600183
4
0
[[3 3 3]
 [4 2 3]
 [5 0 4]
 [2 8 9]]
[[ 9  9  9]
 [16  4  9]
 [25  0 16]
 [ 4 64 81]]
[3 3 3] + [9 9 9] = [12 12 12]
[4 2 3] + [16  4  9] = [20  6 12]
[5 0 4] + [25  0 16] = [30  0 20]
[2 8 9] + [ 4 64 81] = [ 6 72 90]
